- name: variables from PLAY level
  hosts: localhost
  vars_files:
  - variables.yaml
  vars_prompt:
  - name: PERSON
    prompt: please enter your name
    private: false #user can see what thet are entering
  - name: WISHES
    prompt: please enter your wishes
    private: true #user can't see what thet are entering
  vars:
    PERSON: "siva from PLAY"
    WISHES: "Morning from PLAY"
  tasks:
    - name: check variables
      vars:
      PERSON: "siva from PLAY"
      WISHES: "Morning from PLAY"
      ansible.builtin.debug:
        msg: "Hello {{PERSON}}, Good {{WISHES}}"




#1.CMD

  